import { Component } from '@angular/core';
import { CommonModule, CurrencyPipe } from '@angular/common';
import { BeerTap } from '../../models/beer-tap.model';

@Component({
  selector: 'app-blackboard-page',
  imports: [CommonModule, CurrencyPipe],
  templateUrl: './blackboard-page.html',
  styleUrl: './blackboard-page.scss',
})
export class BlackboardPage {


  beers: BeerTap[] = [
    {
      tap: 1,
      name: 'Crazy IPA',
      style: 'IPA',
      brewery: 'Bukowski Brewing',
      location: 'Madrid',
      abv: 6.5,
      halfPrice: 2.8,
      pintPrice: 5.5,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    }
  ];

}
