import { BeerTap } from "../app/models/beer-tap.model";

export const BEERTAP_ITEMS: BeerTap[] = [
    {
      tap: 1,
      name: 'Crazy IPA',
      style: 'IPA',
      brewery: 'Bukowski Brewing',
      location: 'Madrid',
      abv: 6.5,
      halfPrice: 2.8,
      pintPrice: 5.5,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    },
    {
      tap: 2,
      name: 'Dark Soul',
      style: 'Stout',
      brewery: 'Black Barrel',
      location: 'Dublín',
      abv: 7.2,
      halfPrice: 3.0,
      pintPrice: 6.0,
    }
];